---
- name: Install and run Nginx
  hosts: webserver
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      notify: Start Nginx

    - name: Allow HTTP traffic on UFW
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
